#cloud-config
---
write_files:
  # Network config file for the Calico CNI plugin.
  - path: /etc/rkt/net.d/10-calico.conf 
    owner: root
    permissions: 0755
    content: |
      {
          "name": "calico-network",
          "type": "calico",
          "etcd_authority": "$private_ipv4:2379",
          "log_level": "info",
          "ipam": {
              "type": "calico-ipam"
          }
      }
coreos:
  update:
    reboot-strategy: off
  etcd2:
    name: "etcdserver"
    listen-client-urls: http://0.0.0.0:2379
    advertise-client-urls: http://$private_ipv4:2379
    initial-cluster: etcdserver=http://$private_ipv4:2380
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://0.0.0.0:2380    
  units:
    - name: "etcd2.service"
      command: "start"
    - name: calico-node.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=calicoctl node
        After=docker.service etcd2.service
        Requires=docker.service etcd2.service
        
        [Service]
        User=root
        Environment=ETCD_AUTHORITY=$private_ipv4:2379
        PermissionsStartOnly=true
        ExecStartPre=/usr/bin/wget -N -P /opt/bin http://www.projectcalico.org/builds/calicoctl         
        ExecStartPre=/usr/bin/chmod +x /opt/bin/calicoctl
        ExecStart=/opt/bin/calicoctl node --detach=false
        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target