# Relates to https://github.com/golangci/golangci-lint/issues/658#issuecomment-527834647
# Should be removed after the next go-build release (golangci-lint is already upgraded to v1.19.x there)
issues:
  exclude:
  - "not declared by package utf8"
  - "unicode/utf8/utf8.go"
