version: 2
jobs:
  build:
    machine: true
    working_directory: ~/projectcalico/calicoctl
    environment:
      CIRCLE_ARTIFACTS: ~/projectcalico/calicoctl/dist
    steps:
    - checkout
    - run: make binary-containerized
    - store_artifacts:
      path: ~/projectcalico/calicoctl/dist
  
